[[install]]
id = 'aria2-config'
dst = '~/.config/aria2/'
path = 'config'
capabilities = ['develop']
planes = ['user']
actions = ['aria2-install']

[[install]]
id = 'aria2-service'
dst = '~/.config/systemd/user/'
path = 'service'
capabilities = ['develop']
planes = ['user']

[actions]
aria2-install = 'mkdir -p {{@@ sysenv.xdg_state_home @@}}/aria2 && touch {{@@ sysenv.xdg_state_home @@}}/aria2/aria2.session && mkdir -p {{@@ sysenv.xdg_cache_home @@}}/aria2 && touch {{@@ sysenv.xdg_cache_home @@}}/aria2/aria2.log'

[variables.aria2]
port = 16000

[dynvariables]
aria2_bin = 'command -v aria2c 2>/dev/null || echo /usr/bin/aria2c'
aria2_secret_key = """f="{{@@ env['HOME'] @@}}/.local/state/dotfiles/aria2_secret_key"; mkdir -p "$(dirname "$f")"; [ -f "$f" ] && cat "$f" || openssl rand -hex 12 | tee "$f""""
