d   {{@@ env['XDG_RUNTIME_DIR'] @@}}/issues   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   2w

# Language server dirs -- clangd
d   {{@@ lsp.clangd_runtime_dir @@}}/global   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   4w
L+  {{@@ sysenv.xdg_cache_home @@}}/clangd   -   -   -   -   {{@@ lsp.clangd_runtime_dir @@}}/global
