## ccache temporary dirs
d   {{@@ ccache.runtime_dir @@}}   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   -
d   {{@@ ccache.remote_dir @@}}   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   4w
d   {{@@ ccache.tmp_dir @@}}   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   1w
