# -*- mode: sh; sh-shell: sh; coding: utf-8; indent-tabs-mode: nil; -*-
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} modprobe.blacklist=radeon"
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} amdgpu.gpu_recovery=1"
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} amdgpu.dpm=1"
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} amdgpu.ppfeaturemask=0xfffd3fff"
{%@@ for param in grub.amdgpu.kernel_parameters @@%}
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} {{@@ param @@}}"
{%@@ endfor @@%}
