# -*- mode: ssh-config; coding: utf-8; indent-tabs-mode: nil; -*-
# https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
# https://docs.gitlab.com/ee/user/gitlab_com
# https://garbers.co.za/2014/03/03/connecting-to-bitbucket-on-https-port
{%@@ for key, val in ssh.items() @@%}
{%@@ if val is mapping and val.remote is defined @@%}

Host {{@@ val.remote @@}} {{@@ val.url @@}}
    Hostname {{@@ val.hostname @@}}
    User git
    Port {{@@ val.port @@}}
    PreferredAuthentications publickey
    IdentitiesOnly yes
    IdentityFile {{@@ _dotfile_abs_dst @@}}/{{@@ ssh.overlay.identity_prefix @@}}-{{@@ ssh.overlay.identity_key @@}}
    ControlMaster auto
    ControlPath {{@@ env['HOME'] @@}}/.ssh/cm-%C:%n
    ControlPersist 30m
{%@@ endif @@%}
{%@@ endfor @@%}
