//! Writing the plan out as the files Dotdrop reads.
//!
//! Dotdrop accepts TOML wherever it accepts YAML — it dispatches on the file
//! extension for the main config and for every `import_*` target alike — so the
//! generated tree is TOML end to end, in the same language as its own inputs.
//! That is not cosmetic: it means the only translation step in the pipeline is
//! *structural*, and a person reading a generated file is reading the same
//! syntax they wrote.
//!
//! There are two kinds of file, and the line between them is the encryption
//! boundary. `bundle/` holds variables and actions, split so that each overlay's
//! private values sit in their own file under their own transcrypt key. Each
//! entrypoint holds everything else for one host: its settings, its dotfiles,
//! and its profile.
//!
//! Nothing is shared between entrypoints, which costs some duplication and buys
//! the two things that duplication is the only way to get — see
//! [`Entrypoint`](super::resolve::Entrypoint).

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use toml::{Table, Value};

use super::layout::CONFIG_NAME;
use super::resolve::{Entrypoint, Plan};
use super::tree::Repo;

/// The banner every generated file carries. It names the layout declaration
/// rather than any concrete source path, because the concrete paths are that
/// file's to choose — and a banner that lies about where to edit is worse than
/// none.
fn header(config_name: &str) -> String {
    format!(
        "# Generated by `wits dotfiles generate`. Do not edit.\n\
         # Edit the manifests instead; {config_name} says where they are.\n"
    )
}

/// What one `generate` run did, for the summary line.
#[derive(Default)]
pub struct Report {
    pub written: Vec<PathBuf>,
    pub unchanged: usize,
}

/// Render every artifact and write the ones whose content actually changed.
///
/// Skipping identical files is not an optimisation: this output is committed,
/// so rewriting a byte-identical file would put noise in `git status` and make
/// "did regenerating change anything?" — the question you ask after editing a
/// manifest — impossible to answer at a glance.
pub fn generate(repo: &Repo, plan: &Plan) -> Result<Report> {
    let layout = repo.layout();
    let mut report = Report::default();

    let mut shared = Table::new();
    shared.insert("variables".into(), Value::Table(plan.variables.clone()));
    shared.insert(
        "dynvariables".into(),
        Value::Table(plan.dynvariables.clone()),
    );
    write(repo, &layout.variables_file(), &shared, &mut report)?;

    let mut actions = Table::new();
    actions.insert("actions".into(), Value::Table(plan.actions.clone()));
    write(repo, &layout.actions_file(), &actions, &mut report)?;

    for (overlay, aggregate) in &plan.overlay_variables {
        let mut doc = Table::new();
        doc.insert(
            "variables".into(),
            Value::Table(aggregate.variables.clone()),
        );
        if !aggregate.dynvariables.is_empty() {
            doc.insert(
                "dynvariables".into(),
                Value::Table(aggregate.dynvariables.clone()),
            );
        }
        write(
            repo,
            &layout.overlay_variables_file(overlay),
            &doc,
            &mut report,
        )?;
    }

    for entry in &plan.entrypoints {
        write(repo, &entry.path, &entrypoint_document(entry), &mut report)?;
    }

    Ok(report)
}

/// One host's complete Dotdrop config: settings, its dotfiles, its profile.
fn entrypoint_document(entry: &Entrypoint) -> Table {
    let mut entries = Table::new();
    for (id, dotfile) in &entry.dotfiles {
        let mut entry = Table::new();
        entry.insert("dst".into(), Value::String(dotfile.dst.clone()));
        entry.insert("src".into(), Value::String(dotfile.src.clone()));
        if let Some(link) = &dotfile.link {
            entry.insert("link".into(), Value::String(link.clone()));
        }
        if let Some(chmod) = &dotfile.chmod {
            entry.insert("chmod".into(), Value::String(chmod.clone()));
        }
        if !dotfile.actions.is_empty() {
            entry.insert(
                "actions".into(),
                Value::Array(
                    dotfile
                        .actions
                        .iter()
                        .map(|a| Value::String(a.clone()))
                        .collect(),
                ),
            );
        }
        entries.insert(id.clone(), Value::Table(entry));
    }

    let mut profile = Table::new();
    profile.insert(
        "dotfiles".into(),
        Value::Array(
            entry
                .profile
                .dotfiles
                .iter()
                .map(|d| Value::String(d.clone()))
                .collect(),
        ),
    );
    profile.insert(
        "variables".into(),
        Value::Table(entry.profile.variables.clone()),
    );
    let mut profiles = Table::new();
    profiles.insert(entry.host.clone(), Value::Table(profile));

    let mut doc = Table::new();
    doc.insert("config".into(), Value::Table(entry.config.clone()));
    doc.insert("dotfiles".into(), Value::Table(entries));
    doc.insert("profiles".into(), Value::Table(profiles));
    doc
}

/// Write one document at a root-relative path, unless it is already there.
///
/// Skipping identical files is not an optimisation: this output is committed, so
/// rewriting a byte-identical file would put noise in `git status` and make "did
/// regenerating change anything?" — the question you ask after editing a
/// manifest — impossible to answer at a glance.
fn write(repo: &Repo, relative: &Path, document: &Table, report: &mut Report) -> Result<()> {
    let body = format!("{}\n{}", header(CONFIG_NAME), toml::to_string(document)?);
    let path = repo.abs(relative);

    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == body) {
        report.unchanged += 1;
        return Ok(());
    }
    if wits_util::log::is_dry_run() {
        wits_util::log::dry_run(&format!("write {}", relative.display()));
        report.written.push(relative.to_path_buf());
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(&path, &body).with_context(|| format!("writing {}", path.display()))?;
    report.written.push(relative.to_path_buf());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// TOML cannot express a bare key after a table header, so a document with
    /// both must be emitted scalars-first. We rely on the serializer for that
    /// rather than pre-sorting; this pins the behaviour, because getting it
    /// wrong produces a file that is invalid rather than merely ugly.
    #[test]
    fn scalars_are_emitted_before_tables_regardless_of_key_order() {
        let mut inner = Table::new();
        inner.insert("aaa_table".into(), {
            let mut t = Table::new();
            t.insert("k".into(), Value::Integer(1));
            Value::Table(t)
        });
        inner.insert("zzz_scalar".into(), Value::Integer(2));
        let mut doc = Table::new();
        doc.insert("variables".into(), Value::Table(inner));

        let text = toml::to_string(&doc).unwrap();
        let reparsed: Table = text.parse().expect("emitted TOML must reparse");
        assert_eq!(reparsed["variables"]["zzz_scalar"].as_integer(), Some(2));
        assert_eq!(
            reparsed["variables"]["aaa_table"]["k"].as_integer(),
            Some(1)
        );
    }

    #[test]
    fn an_identical_file_is_not_rewritten() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join(CONFIG_NAME),
            "[layout]\ncomposition = 'hosts.toml'\n",
        )
        .unwrap();
        std::fs::write(dir.path().join("hosts.toml"), "").unwrap();
        let repo = Repo::open(None, Some(dir.path())).unwrap();

        let relative = Path::new("out/deep/file.toml");
        let mut doc = Table::new();
        doc.insert("k".into(), Value::Integer(1));

        let mut first = Report::default();
        write(&repo, relative, &doc, &mut first).unwrap();
        assert_eq!(first.written, vec![relative.to_path_buf()]);
        assert!(dir.path().join(relative).is_file(), "parents are created");

        let mut second = Report::default();
        write(&repo, relative, &doc, &mut second).unwrap();
        assert!(second.written.is_empty());
        assert_eq!(second.unchanged, 1);
    }

    /// Dotdrop rejects a config missing any of the three top-level sections, so
    /// a host that deploys nothing still needs the empty tables spelled out.
    #[test]
    fn an_entrypoint_always_has_all_three_sections() {
        let doc = entrypoint_document(&Entrypoint {
            plane: "user".into(),
            host: "alpha".into(),
            path: PathBuf::from("out/user.alpha.toml"),
            config: Table::new(),
            dotfiles: Default::default(),
            profile: super::super::resolve::Profile {
                dotfiles: Vec::new(),
                variables: Table::new(),
            },
        });

        assert!(doc.contains_key("config"));
        assert!(doc.contains_key("dotfiles"));
        assert_eq!(
            doc["profiles"]["alpha"]["dotfiles"]
                .as_array()
                .unwrap()
                .len(),
            0
        );
    }
}
