[[install]]
id = 'ssh'
dst = '~/.ssh/'
path = '.'
capabilities = ['develop']
planes = ['user']

[variables.ssh.github]
remote = 'github'
url = 'github.com'
hostname = 'ssh.github.com'
port = 443

[variables.ssh.gitlab]
remote = 'gitlab'
url = 'gitlab.com'
hostname = 'altssh.gitlab.com'
port = 443

[variables.ssh.codeberg]
remote = 'codeberg'
url = 'codeberg.org'
hostname = 'codeberg.org'
port = 22
