[[install]]
id = 'emacs'
dst = '~/.config/emacs/'
path = '.'
capabilities = ['develop']
planes = ['user']
link = 'absolute'
actions = ['emacs-config']

[actions]
emacs-config = '''{{@@ _dotfile_abs_dst @@}}/bin/ginshio-emacs sync'''
