[project]
org = "{{@@ wits.projects.source_info['llvm'].org @@}}"
build_system = "cmake"
generator = "Ninja"
toolchain = "clang"
default_presets = ["common"]

[repos.main]
path = "{{@@ projects.root_dir @@}}/{{project.org}}/{{project.name}}"
source_dir = "{{repos.main.workdir}}/llvm"
build_dir = "{{repos.main.workdir}}/_build/{{branch.slug}}-{{build_type}}"
install_dir = "{{repos.main.workdir}}/_build/{{branch.slug}}-{{build_type}}"
main_branch = "main"
[repos.main.remotes]
upstream = "https://github.com/llvm/llvm-project.git"
origin = "https://github.com/GinShio/llvm-project.git"

[project.presets.common]
extends = ["llvm/common"]
[project.presets.common.definitions]
BUILD_SHARED_LIBS = true
LLVM_ENABLE_ASSERTIONS = true
LLVM_BUILD_TESTS = true
LLVM_BUILD_TOOLS = true
LLVM_ENABLE_PIC = true
LLVM_ENABLE_PROJECTS = "clang;mlir;lld"
LLVM_ENABLE_RTTI = false
LLVM_INCLUDE_TOOLS = true
LLVM_TARGETS_TO_BUILD = "AMDGPU;RISCV;X86"
CLANG_ENABLE_CIR = true

[project.presets.experimental.definitions]
LLVM_EXPERIMENTAL_TARGETS_TO_BUILD = "DirectX;SPIRV"
CLANG_ENABLE_HLSL = true

[project.presets.alive2.definitions]
LLVM_ENABLE_RTTI = true
