d   {{@@ lsp.clangd_runtime_dir @@}}/mesa   0700   {{@@ env['USER'] @@}}   {{@@ env['USER'] @@}}   -
L+  {{@@ projects.root_dir @@}}/{{@@ wits.projects.source_info['mesa'].org @@}}/{{@@ wits.projects.source_info['mesa'].name @@}}/.cache   -   -   -   -   {{@@ lsp.clangd_runtime_dir @@}}/mesa
