[variables.agents.vendors]
claude = 'openrouter'
codex  = 'openrouter'
pi     = 'openrouter'

[variables.agents.model.openrouter]
default     = "z-ai/glm-5.3-flash"
turing      = "z-ai/glm-5.3-flash"
wintermute  = "z-ai/glm-5.3-flash"
neuromancer = "z-ai/glm-5.3-flash"
subagent    = "z-ai/glm-5.3-flash"
