[variables.agents.vendors]
claude = 'openrouter'
codex  = 'openrouter'
cursor = 'openrouter'

[variables.agents.model.openrouter]
default     = "deepseek/deepseek-v4-flash-0731[1m]"
turing      = "deepseek/deepseek-v4-flash-0731[1m]"
wintermute  = "deepseek/deepseek-v4-flash-0731[1m]"
neuromancer = "deepseek/deepseek-v4-flash-0731[1m]"
subagent    = "deepseek/deepseek-v4-flash-0731[1m]"
