# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[blame]
        # Mark lines that are ignored by .gitignore in blame output
        markIgnoredLines = true
        # Mark lines that cannot be blamed (e.g., binary files or ignored lines) in blame output
        markUnblamableLines = true
