# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[fetch]
        # Let Git choose the number of parallel fetches
        parallel = 0
        # Prune remote-tracking branches that no longer exist on the remote
        prune = true
        # Write commit graph after fetch to improve performance
        writeCommitGraph = true
