# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[user]
        # Require an explicit identity instead of guessing one from the system
        useConfigOnly = true

[include]
        path = personal_dispatch.conf
        path = personal_transcrypt.conf
{%@@ if "khronos3d" in overlays @@%}
        path = khronos3d_dispatch.conf
        path = khronos3d_transcrypt.conf
{%@@ endif @@%}
