# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[index]
        # Let Git choose how many threads load the index
        threads = 0
        # Permit a sparse index when cone-mode sparse checkout is enabled
        sparse = true
        # Initialize new indexes with v4 pathname compression
        version = 4
