# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[init]
        # Set the default branch name for new repositories
        defaultBranch = master
        # Specify the global excludes file for new repositories
        excludesFile = {{@@ _dotfile_abs_dst @@}}/ignore
