# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[merge]
        # Show diff3 style for merge conflicts, including the common ancestor
        conflictstyle = diff3
        # Only allow fast-forward merges, abort if not possible
        ff = only
        # Set the default merge tool to ediff
        tool = ediff

[mergetool.ediff]
        # Command to run ediff for merging files with ancestor
        cmd = emacsclient -nw --eval \"(ginshio/git-mergetool \\\"$LOCAL\\\" \\\"$REMOTE\\\" \\\"$BASE\\\" \\\"$MERGED\\\")\"
