# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[pack]
        # Number of threads to use for packing operations (0 means use all available CPU cores)
        threads = 0
        # Use sparse pack for better performance in large repositories
        useSparse = true
