# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[user]
        # Set the user name for commits
        name = GinShio
        # Set the user email for commits
        email = ginshio78@gmail.com
