# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[url "{{@@ ssh["codeberg"].remote @@}}:"]
        # Rewrite git@codeberg.org: URLs to use codeberg: instead
        insteadOf = git@codeberg.org:
        # Rewrite ssh://git@codeberg.org/ URLs to use codeberg: instead
        insteadOf = ssh://git@codeberg.org/
        # Rewrite https://codeberg.org/ push URLs to use codeberg: instead
        pushInsteadOf = https://codeberg.org/

[include]
        # Include personal identity configuration for Codeberg
        path = personal_identity.conf
        path = personal_secrets.conf
