# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[url "{{@@ ssh["bitbucket"].remote @@}}:"]
        # Rewrite git@bitbucket.org: URLs to use bitbucket: instead
        insteadOf = git@bitbucket.org:
        # Rewrite ssh://git@bitbucket.org/ URLs to use bitbucket: instead
        insteadOf = ssh://git@bitbucket.org/
        # Rewrite https://bitbucket.org/ push URLs to use bitbucket: instead
        pushInsteadOf = https://bitbucket.org/

[include]
        # Include personal identity configuration for Bitbucket
        path = personal_identity.conf
        path = personal_secrets.conf
