# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[url "{{@@ ssh["github"].remote @@}}:"]
        # Rewrite git@github.com: URLs to use github: instead
        insteadOf = git@github.com:
        # Rewrite ssh://git@github.com/ URLs to use github: instead
        insteadOf = ssh://git@github.com/
        # Rewrite https://github.com/ push URLs to use github: instead
        pushInsteadOf = https://github.com/

[include]
        # Include personal identity configuration for GitHub
        path = personal_identity.conf
        path = personal_secrets.conf
