# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[pull]
        # Only allow fast-forward pulls, abort if merge is needed
        ff = only
        # Keep pull from starting an implicit rebase
        rebase = false
