# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[push]
        # Push the current branch to a branch of the same name on the remote
        default = current
        # With implicit leases, require the remote tip in local reflog history
        # See git-push(1), --force-if-includes
        useForceIfIncludes = true
