# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[rebase]
        # Automatically squash fixup and squash commits during rebase
        autoSquash = true
        # Automatically stash and unstash changes during rebase
        autoStash = true
