# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[status]
        # Show tracking and push positions; Git suppresses duplicate comparisons
        compareBranches = @{upstream} @{push}
